### PR TITLE
removing bluebird promises

### PR DESCRIPTION
**Pull request by fgonzaleziv**
Removing bluebird from framework
RE: [#14482](https://github.com/TryGhost/Ghost/issues/14882)

Tests are passing locally, but let me know if I need to make any other changes.

Thanks!

### CODE REVIEW

**Comment by ErisDS** [comment]
Hey @fgonzaleziv thank you for this PR :) I'm not sure how your tests are passing locally as there is no native `Promise.reduce` function. Bluebird must still be loading for you.

On CI you can see a tonne of `TypeError: Promise.reduce is not a function` errors.

Removing bluebird here will require a refactor of those methods to use a native equivalent.

**Comment by fgonzaleziv** [comment]
Looks like it still is. The pipeline test results will be very helpful. Thanks!

**Comment by ErisDS** [comment]
@fgonzaleziv did you mean to close this?

**Comment by fgonzaleziv** [comment]
@ErisDS Yes, I must not have it setup correctly on local since tests are giving different results. I closed it since I need to make more changes to the code as well as fix my dev setup. (I just found the developer forums). Thanks for the help so far!

**Comment by ErisDS** [comment]
Hey @fgonzaleziv, just so you don't spend more time on this I wanted to let you know these changes have been completed now

**Pull request closed without merging**
